import type { Snapshot, SnapshotCreateInput } from "../src/shared/types";

export const baseSnapshotInput: SnapshotCreateInput = {
  observed_date: "2026-06-03",
  observed_time: "23:59",
  timezone: "Asia/Tokyo",
  game_mode: "south",
  player_name: "Player",
  player_id: "player-1",
  rank_name: "雀士",
  rank_level: 1,
  rank_points: 1200,
  rank_points_max: 2000,
  matches: 100,
  avg_win_score: 7200,
  avg_place: 2.5,
  max_renchan: 3,
  avg_win_turn: 9.2,
  first_rate: 25,
  second_rate: 25,
  third_rate: 25,
  fourth_rate: 25,
  bust_rate: null,
  win_rate: 25,
  tsumo_rate: 30,
  deal_in_rate: 12,
  call_rate: 35,
  riichi_rate: 18,
  note: "Focused on defense.",
  source_image_sha256: null,
  file_name: null,
  file_last_modified: null,
  exif_taken_at: null,
  image_width: null,
  image_height: null,
  parser_version: "manual-v1"
};

export function makeSnapshot(overrides: Partial<Snapshot> = {}): Snapshot {
  return {
    id: 1,
    observed_date: baseSnapshotInput.observed_date,
    observed_time: baseSnapshotInput.observed_time,
    timezone: baseSnapshotInput.timezone,
    game_mode: baseSnapshotInput.game_mode,
    player_name: baseSnapshotInput.player_name ?? null,
    player_id: baseSnapshotInput.player_id ?? null,
    rank_name: baseSnapshotInput.rank_name ?? null,
    rank_level: baseSnapshotInput.rank_level ?? null,
    rank_points: baseSnapshotInput.rank_points ?? null,
    rank_points_max: baseSnapshotInput.rank_points_max ?? null,
    matches: baseSnapshotInput.matches,
    avg_win_score: baseSnapshotInput.avg_win_score ?? null,
    avg_place: baseSnapshotInput.avg_place,
    max_renchan: baseSnapshotInput.max_renchan ?? null,
    avg_win_turn: baseSnapshotInput.avg_win_turn ?? null,
    first_rate: baseSnapshotInput.first_rate,
    second_rate: baseSnapshotInput.second_rate,
    third_rate: baseSnapshotInput.third_rate,
    fourth_rate: baseSnapshotInput.fourth_rate,
    bust_rate: baseSnapshotInput.bust_rate ?? null,
    win_rate: baseSnapshotInput.win_rate,
    tsumo_rate: baseSnapshotInput.tsumo_rate ?? null,
    deal_in_rate: baseSnapshotInput.deal_in_rate,
    call_rate: baseSnapshotInput.call_rate,
    riichi_rate: baseSnapshotInput.riichi_rate,
    note: baseSnapshotInput.note ?? null,
    source_image_sha256: baseSnapshotInput.source_image_sha256 ?? null,
    file_name: baseSnapshotInput.file_name ?? null,
    file_last_modified: baseSnapshotInput.file_last_modified ?? null,
    exif_taken_at: baseSnapshotInput.exif_taken_at ?? null,
    image_width: baseSnapshotInput.image_width ?? null,
    image_height: baseSnapshotInput.image_height ?? null,
    parser_version: baseSnapshotInput.parser_version ?? null,
    observed_at_utc: "2026-06-03T14:59:00.000Z",
    source_image_stored: 0,
    created_at: "2026-06-03T15:00:00.000Z",
    updated_at: "2026-06-03T15:00:00.000Z",
    ...overrides
  };
}
